name: 'Build (legacy v5)'
description: 'Build the project'

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/yarn-install@v4

    - name: 'Cache build'
      uses: actions/cache@v4
      id: cache-build
      with:
        path: |
          ./dist
        key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/src') }}

    - name: 'Create build'
      if: steps.cache-build.outputs.cache-hit != 'true'
      run: yarn build
      shell: bash
