/* eslint-disable max-lines-per-function */
import {
  AUSTRIA,
  BELGIUM,
  BULGARIA,
  CROATIA,
  CZECH_REPUBLIC,
  DENMARK,
  ESTONIA,
  FINLAND,
  FRANCE,
  GERMANY,
  GREECE,
  HUNGARY,
  IRELAND,
  ITALY,
  LATVIA,
  LIECHTENSTEIN,
  LITHUANIA,
  LUXEMBOURG,
  NETHERLANDS,
  POLAND,
  PORTUGAL,
  ROMANIA,
  SLOVAKIA,
  SLOVENIA,
  SPAIN,
  SWEDEN,
  UNITED_KINGDOM,
} from '@myparcel/constants/countries';
import {CarrierName, DeliveryTypeName, PackageTypeName, ShipmentOptionName} from '@myparcel/constants';
import {type PlatformConfiguration} from '../types';
import {AddressField, CarrierSetting, SubscriptionType, CustomDeliveryType, ConfigSetting} from '../data';

export const getMyParcelConfig = (): PlatformConfiguration => ({
  carriers: [
    {
      name: CarrierName.PostNl,
      subscription: SubscriptionType.Optional,
      packageTypes: [
        PackageTypeName.Package,
        PackageTypeName.Mailbox,
        PackageTypeName.DigitalStamp,
        PackageTypeName.PackageSmall,
      ],
      deliveryTypes: [
        DeliveryTypeName.Standard,
        DeliveryTypeName.Morning,
        DeliveryTypeName.Evening,
        DeliveryTypeName.Pickup,
        CustomDeliveryType.Monday,
      ],
      deliveryCountries: [NETHERLANDS, BELGIUM],
      pickupCountries: [NETHERLANDS, BELGIUM, DENMARK, SWEDEN, GERMANY],
      smallPackagePickupCountries: [NETHERLANDS, BELGIUM],
      fakeDelivery: true,
      shipmentOptionsPerPackageType: {
        [PackageTypeName.Package]: [ShipmentOptionName.OnlyRecipient, ShipmentOptionName.Signature],
        [PackageTypeName.PackageSmall]: [ShipmentOptionName.OnlyRecipient, ShipmentOptionName.Signature],
      },
      features: [
        CarrierSetting.DeliveryDaysWindow,
        CarrierSetting.DropOffDays,
        CarrierSetting.DropOffDelay,
        ConfigSetting.PickupMapAllowLoadMore,
      ],
      addressFields: [AddressField.PostalCode, AddressField.Street, AddressField.City],
    },
    {
      name: CarrierName.DhlForYou,
      subscription: SubscriptionType.Optional,
      packageTypes: [PackageTypeName.Package, PackageTypeName.Mailbox, PackageTypeName.PackageSmall],
      deliveryTypes: [DeliveryTypeName.Standard, DeliveryTypeName.Pickup, CustomDeliveryType.SameDay],
      deliveryCountries: [NETHERLANDS, BELGIUM],
      pickupCountries: [NETHERLANDS, BELGIUM],
      smallPackagePickupCountries: [NETHERLANDS, BELGIUM],
      shipmentOptionsPerPackageType: {
        [PackageTypeName.Package]: [ShipmentOptionName.OnlyRecipient, ShipmentOptionName.Signature],
      },
      features: [CarrierSetting.DeliveryDaysWindow, CarrierSetting.DropOffDays, CarrierSetting.DropOffDelay],
      addressFields: [AddressField.City, AddressField.PostalCode],
    },
    {
      name: CarrierName.DhlParcelConnect,
      subscription: SubscriptionType.Optional,
      packageTypes: [PackageTypeName.Package],
      deliveryTypes: [DeliveryTypeName.Standard, DeliveryTypeName.Pickup],
      deliveryCountries: [
        AUSTRIA,
        BULGARIA,
        CROATIA,
        CZECH_REPUBLIC,
        ESTONIA,
        FINLAND,
        GERMANY,
        GREECE,
        HUNGARY,
        IRELAND,
        ITALY,
        LATVIA,
        LITHUANIA,
        LUXEMBOURG,
        POLAND,
        PORTUGAL,
        ROMANIA,
        SLOVAKIA,
        SLOVENIA,
        SPAIN,
      ],
      pickupCountries: [
        AUSTRIA,
        BULGARIA,
        CROATIA,
        CZECH_REPUBLIC,
        DENMARK,
        FRANCE,
        GERMANY,
        GREECE,
        HUNGARY,
        ITALY,
        LUXEMBOURG,
        POLAND,
        PORTUGAL,
        ROMANIA,
        SLOVAKIA,
        SLOVENIA,
        SPAIN,
        SWEDEN,
      ],
      features: [],
    },
    {
      name: CarrierName.DhlEuroPlus,
      subscription: SubscriptionType.Optional,
      packageTypes: [PackageTypeName.Package],
      deliveryTypes: [DeliveryTypeName.Standard],
      deliveryCountries: [
        BELGIUM,
        BULGARIA,
        DENMARK,
        GERMANY,
        ESTONIA,
        FINLAND,
        FRANCE,
        GREECE,
        HUNGARY,
        IRELAND,
        ITALY,
        CROATIA,
        LATVIA,
        LITHUANIA,
        LUXEMBOURG,
        NETHERLANDS,
        AUSTRIA,
        POLAND,
        PORTUGAL,
        ROMANIA,
        SLOVENIA,
        SLOVAKIA,
        SPAIN,
        CZECH_REPUBLIC,
        SWEDEN,
        UNITED_KINGDOM,
      ],
      features: [],
    },
    {
      name: CarrierName.UpsStandard,
      subscription: SubscriptionType.Required,
      packageTypes: [PackageTypeName.Package],
      deliveryTypes: [DeliveryTypeName.Standard, DeliveryTypeName.Pickup],
      deliveryCountries: [
        AUSTRIA,
        BELGIUM,
        BULGARIA,
        GERMANY,
        ESTONIA,
        FINLAND,
        GREECE,
        HUNGARY,
        IRELAND,
        ITALY,
        CROATIA,
        LATVIA,
        LITHUANIA,
        LUXEMBOURG,
        NETHERLANDS,
        POLAND,
        PORTUGAL,
        ROMANIA,
        SLOVENIA,
        SLOVAKIA,
        SPAIN,
        CZECH_REPUBLIC,
      ],
      pickupCountries: [GERMANY],
      addressFields: [AddressField.PostalCode, AddressField.Street, AddressField.City],
    },
    {
      name: CarrierName.UpsExpressSaver,
      subscription: SubscriptionType.Required,
      packageTypes: [PackageTypeName.Package],
      deliveryTypes: [DeliveryTypeName.Express, DeliveryTypeName.Pickup],
      deliveryCountries: [
        AUSTRIA,
        BELGIUM,
        BULGARIA,
        GERMANY,
        ESTONIA,
        FINLAND,
        GREECE,
        HUNGARY,
        IRELAND,
        ITALY,
        CROATIA,
        LATVIA,
        LITHUANIA,
        LUXEMBOURG,
        NETHERLANDS,
        POLAND,
        PORTUGAL,
        ROMANIA,
        SLOVENIA,
        SLOVAKIA,
        SPAIN,
        CZECH_REPUBLIC,
      ],
      pickupCountries: [GERMANY],
      addressFields: [AddressField.PostalCode, AddressField.Street, AddressField.City],
      unsupportedParameters: ['package_type'],
    },
    {
      name: CarrierName.Dpd,
      subscription: SubscriptionType.Required,
      packageTypes: [PackageTypeName.Package, PackageTypeName.Mailbox],
      deliveryTypes: [DeliveryTypeName.Standard, DeliveryTypeName.Pickup],
      deliveryCountries: [
        AUSTRIA,
        BELGIUM,
        BULGARIA,
        CZECH_REPUBLIC,
        DENMARK,
        ESTONIA,
        FINLAND,
        FRANCE,
        GERMANY,
        GREECE,
        HUNGARY,
        IRELAND,
        ITALY,
        LATVIA,
        LIECHTENSTEIN,
        LITHUANIA,
        LUXEMBOURG,
        NETHERLANDS,
        POLAND,
        PORTUGAL,
        ROMANIA,
        SLOVAKIA,
        SLOVENIA,
        SPAIN,
        SWEDEN,
      ],
      pickupCountries: [
        AUSTRIA,
        BELGIUM,
        CZECH_REPUBLIC,
        DENMARK,
        ESTONIA,
        FINLAND,
        FRANCE,
        GERMANY,
        HUNGARY,
        LATVIA,
        LITHUANIA,
        LUXEMBOURG,
        NETHERLANDS,
        POLAND,
        PORTUGAL,
        SLOVAKIA,
        SLOVENIA,
        SPAIN,
        UNITED_KINGDOM,
      ],
      features: [CarrierSetting.DropOffDays, CarrierSetting.DropOffDelay],
      addressFields: [AddressField.PostalCode, AddressField.Street, AddressField.City],
    },
  ],
});
