import {
  AUSTRIA,
  BELGIUM,
  BULGARIA,
  CZECH_REPUBLIC,
  DENMARK,
  ESTONIA,
  FINLAND,
  FRANCE,
  GERMANY,
  GREECE,
  HUNGARY,
  IRELAND,
  ITALY,
  LATVIA,
  LIECHTENSTEIN,
  LITHUANIA,
  LUXEMBOURG,
  NETHERLANDS,
  POLAND,
  PORTUGAL,
  ROMANIA,
  SLOVAKIA,
  SLOVENIA,
  SPAIN,
  SWEDEN,
  UNITED_KINGDOM,
} from '@myparcel/constants/countries';
import {CarrierName, DeliveryTypeName, PackageTypeName, ShipmentOptionName} from '@myparcel/constants';
import {type PlatformOptions} from '../types';
import {AddressField, CarrierSetting, SubscriptionType} from '../data';

// eslint-disable-next-line max-lines-per-function
export const getSendMyParcelConfig = (): PlatformOptions => ({
  carriers: [
    {
      name: CarrierName.Bpost,
      subscription: SubscriptionType.Never,
      packageTypes: [PackageTypeName.Package],
      deliveryTypes: [DeliveryTypeName.Standard],
      deliveryCountries: [BELGIUM, NETHERLANDS],
      pickupCountries: [BELGIUM, NETHERLANDS],
      features: [
        CarrierSetting.AllowSaturdayDelivery,
        CarrierSetting.DeliveryDaysWindow,
        CarrierSetting.DropOffDays,
        CarrierSetting.DropOffDelay,
      ],
      addressFields: [AddressField.PostalCode, AddressField.Street, AddressField.City],
      shipmentOptions: [ShipmentOptionName.OnlyRecipient, ShipmentOptionName.Signature],
    },
    {
      name: CarrierName.PostNl,
      subscription: SubscriptionType.Never,
      packageTypes: [PackageTypeName.Package],
      deliveryTypes: [DeliveryTypeName.Standard],
      deliveryCountries: [BELGIUM, NETHERLANDS],
      pickupCountries: [BELGIUM, NETHERLANDS],
      shipmentOptions: [ShipmentOptionName.Signature],
      features: [CarrierSetting.DeliveryDaysWindow, CarrierSetting.DropOffDays, CarrierSetting.DropOffDelay],
    },
    {
      name: CarrierName.Dpd,
      subscription: SubscriptionType.Never,
      packageTypes: [PackageTypeName.Package],
      deliveryTypes: [DeliveryTypeName.Standard, DeliveryTypeName.Pickup],
      deliveryCountries: [
        AUSTRIA,
        BELGIUM,
        BULGARIA,
        CZECH_REPUBLIC,
        DENMARK,
        ESTONIA,
        FINLAND,
        FRANCE,
        GERMANY,
        GREECE,
        HUNGARY,
        IRELAND,
        ITALY,
        LATVIA,
        LIECHTENSTEIN,
        LITHUANIA,
        LUXEMBOURG,
        NETHERLANDS,
        POLAND,
        PORTUGAL,
        ROMANIA,
        SLOVAKIA,
        SLOVENIA,
        SPAIN,
        SWEDEN,
      ],
      pickupCountries: [
        AUSTRIA,
        BELGIUM,
        CZECH_REPUBLIC,
        DENMARK,
        ESTONIA,
        FINLAND,
        FRANCE,
        GERMANY,
        HUNGARY,
        LATVIA,
        LITHUANIA,
        LUXEMBOURG,
        NETHERLANDS,
        POLAND,
        PORTUGAL,
        SLOVAKIA,
        SLOVENIA,
        SPAIN,
        UNITED_KINGDOM,
      ],
      features: [CarrierSetting.DropOffDays, CarrierSetting.DropOffDelay],
      addressFields: [AddressField.PostalCode, AddressField.Street, AddressField.City],
    },
  ],
});
