name: '🔸 Run tests 🧪'

on:
  workflow_call:

jobs:
  test:
    name: 'Run tests'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: 'Cache coverage'
        uses: actions/cache@v3
        id: cache-coverage
        with:
          path: ./coverage
          key: ${{ runner.os }}-coverage-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/src') }}
          restore-keys: |
            ${{ runner.os }}-coverage-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-coverage-

      - uses: myparcelnl/actions/yarn-install@v3
        if: steps.cache-coverage.outputs.cache-hit != 'true'
        with:
          node-version: 16

      - name: 'Run tests'
        if: steps.cache-coverage.outputs.cache-hit != 'true'
        run: ./node_modules/.bin/cross-env yarn test:unit --coverage
        env:
          NODE_ICU_DATA: node_modules/full-icu

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
