name: 'Validate pull request title'

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.number }}'
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - uses: myparcelnl/actions/pr-validate-title-conventional@v4
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}
