name: 'On push (legacy v5) ⚙️'

on:
  push:
    branches:
      - v5.x

    paths-ignore:
      - ./**/*.md
      - ./.idea/**

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/test-v5
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/build-v5

  release:
    runs-on: ubuntu-22.04
    needs:
      - test
      - build
    steps:
      - uses: myparcelnl/actions/setup-git-credentials@v4
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v5
        with:
          token: ${{ steps.credentials.outputs.token }}
          fetch-depth: 0

      - uses: ./.github/actions/build-v5

      - uses: myparcelnl/actions/semantic-release@v4
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          token: ${{ steps.credentials.outputs.token }}

  rebase-prs:
    needs:
      - test
      - build
    uses: ./.github/workflows/rebase-prs.yml
    secrets: inherit
