name: 'Release new version 🚀'

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - beta
      - alpha

    paths-ignore:
      - ./**/*.md
      - ./.idea/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    runs-on: ubuntu-22.04
    needs:
      - test
    steps:
      - uses: myparcelnl/actions/setup-git-credentials@v4
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.credentials.outputs.token }}
          fetch-depth: 0

      - uses: myparcelnl/actions/yarn-install@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - uses: myparcelnl/actions/nx-cache@v4

      - name: 'Import translations'
        shell: bash
        # language=bash
        run: |
          yarn nx run-many \
            --output-style="static" \
            --target="translations:import"

      - name: 'Build'
        shell: bash
        # language=bash
        run: |
          yarn nx run-many \
            --output-style="static" \
            --target="build"

      - name: 'Release'
        working-directory: apps/delivery-options
        # language=bash
        run: |
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.credentials.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # TODO: uncomment when on main
      #      - uses: actions/upload-pages-artifact@v1
      #        with:
      #          path: apps/sandbox/dist

  # TODO: uncomment when on main
  #  deploy:
  #    needs: release
  #    runs-on: ubuntu-22.04
  #    permissions:
  #      pages: write
  #      id-token: write
  #    environment:
  #      name: github-pages
  #      url: ${{ steps.deployment.outputs.page_url }}
  #    steps:
  #      - name: Deploy to GitHub Pages
  #        id: deployment
  #        uses: actions/deploy-pages@v1

  rebase-prs:
    needs: release
    if: always()
    runs-on: ubuntu-22.04
    steps:
      - uses: myparcelnl/actions/setup-git-credentials@v4
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: peter-evans/rebase@v3
        with:
          token: ${{ steps.credentials.outputs.token }}
          base: ${{ github.ref_name }}
          exclude-drafts: true
          exclude-labels: 'dependencies'
