name: 'Run tests 🧪'

on:
  pull_request:
    branches:
      - main
      - beta
      - alpha

    paths-ignore:
      - ./**/*.md
      - ./.idea/**

  merge_group:

concurrency:
  group: '${{ github.workflow }}-${{ github.ref_name }}'
  cancel-in-progress: true

jobs:
  bundlewatch:
    uses: ./.github/workflows/bundlewatch.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
