name: Build

on:
  pull_request:
    paths-ignore:
      - ./**/*.md
      - screenshots/**/*

  push:
    branches:
      - main
    paths:
      - src/**/*
      - public/**/*
      - types/**/*
      - .browserslistrc
      - babel.config.js
      - package-lock.json
      - package.json
      - postcss.config.js
      - vue.config.js

jobs:
  test:
    name: 'Run tests'
    if: contains(github.event.head_commit.message, '[skip ci]') == false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: myparcelnl/actions/yarn-install@v1
      - name: 'Run tests'
        run: ./node_modules/.bin/cross-env yarn test:unit --coverage
        env:
          NODE_ICU_DATA: node_modules/full-icu

      - name: 'Upload code coverage'
        uses: codecov/codecov-action@v1.0.13

  build:
    name: 'Create build'
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
      - uses: myparcelnl/actions/yarn-install@v1
      - run: yarn run build
      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist/

  release:
    name: 'Publish'
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    steps:
      - uses: actions/checkout@v2
      - uses: myparcelnl/actions/yarn-install@v1
      - name: Get build
        uses: actions/download-artifact@v1
        with:
          name: dist

      - uses: myparcelnl/actions/semantic-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: 'Publish updated sandbox'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GH_REPO_TOKEN }}

